---
- name: Create nuage monitor directory 
  become: yes
  file: path={{ nuage_mon_config_dir }} state=directory  

- name: Create the log directory
  become: yes
  file: path={{ nuage_mon_rest_server_logdir }} state=directory

- name: Install Nuage k8s monitor 
  become: yes
  yum: name={{ nuage_monitor_rpm }} state=present

- include: certificates.yml 

- name: Create nuagekubemon.yaml
  become: yes
  template: src=nuagekubemon.yaml.j2 dest={{ nuage_mon_yaml_path }} owner=root mode=0644

- name: Create net-config.yaml
  become: yes
  template: src=net-config.yaml.j2 dest={{ nuage_net_config_yaml_path }} owner=root mode=0644
  notify:
    - restart nuagekubemon
