nuage_mon_config_dir: /usr/share/nuagekubemon
nuage_mon_yaml_path: "{{ nuage_mon_config_dir }}/nuagekubemon.yaml"
nuage_net_config_yaml_path: "{{ nuage_mon_config_dir }}/net-config.yaml"
nuage_mon_rest_server_logdir: /var/log/nuagekubemon

cert_output_dir: "{{ nuage_mon_config_dir }}"
nuage_master_crt_dir: "{{ nuage_mon_config_dir }}"
nuage_mon_rest_server_crt_dir: "{{ nuage_master_crt_dir }}/{{ ansible_nodename }}"
nuage_mon_rest_server_host: "{{ ansible_nodename }}"
nuage_mon_rest_server_port: "{{ nuage_openshift_monitor_rest_server_port | default('9443') }}"
nuage_mon_rest_server_url: "0.0.0.0:{{ nuage_mon_rest_server_port }}"
nuage_ca_master_rest_server_key: "{{ nuage_mon_rest_server_crt_dir }}/nuageMonServer.key"
nuage_ca_master_rest_server_crt: "{{ nuage_mon_rest_server_crt_dir }}/nuageMonServer.crt"

nuage_k8s_kubeconfig: "/etc/kubernetes/nuage.kubeconfig"
nuage_k8s_cert_dir: /etc/kubernetes/certs
nuage_k8s_client_crt: "{{ nuage_k8s_cert_dir }}/nuage.crt"
nuage_k8s_client_key: "{{ nuage_k8s_cert_dir }}/nuage.key"
