---
- name: Install Nuage VRS
  become: yes
  yum: name={{ vrs_rpm }} state=present
  
- name: Set the uplink interface 
  become: yes
  lineinfile: dest={{ vrs_config }} regexp=^NETWORK_UPLINK_INTF line='NETWORK_UPLINK_INTF={{ uplink_interface }}'

- name: Set the Active Controller 
  become: yes
  lineinfile: dest={{ vrs_config }} regexp=^ACTIVE_CONTROLLER line='ACTIVE_CONTROLLER={{ vsc_active_ip }}'

- name: Set the Standby Controller 
  become: yes
  lineinfile: dest={{ vrs_config }} regexp=^STANDBY_CONTROLLER line='STANDBY_CONTROLLER={{ vsc_standby_ip }}'
  when: vsc_standby_ip is defined

- name: Install plugin rpm
  become: yes
  yum: name={{ plugin_rpm }} state=present

- include: certificates.yml

- name: Set the vsp-k8s.yaml 
  become: yes
  template: src=vsp-k8s.j2 dest={{ vsp_k8s_yaml }} owner=root mode=0644

- name: Restart vrs
  become: yes
  service: name=openvswitch state=restarted
